# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: browsercheck

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1

# The `functions` block defines what code to deploy
functions:
  browserCheck:
    handler: handler.landingPage
    # The `events` block defines how to trigger the handler.landingPage code
    events:
      - http:
          path: /
          method: get
          cors: true
